config/routes.rb
Rails.application.routes.draw do
    
    root to: 'toppages#index'
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create] do
      member do
          get :likes
          get :my_comments
      end
    end  
  
  resources :favorites, only: [:create, :destroy]
  resources :subjects, only: [:show, :new, :create, :edit, :update] do
      resources :comments, only: [:create, :edit, :update, :destroy]
  end      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  
  has_many :favorites , dependent: :destroy
  has_many :favoriting_users, through: :favorites, source: :user 

  validates :message, presence: true, length: { maximum: 255 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  
  has_many :comments
  
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
    
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    
    has_many :subjects
    has_many :comments
    has_many :favorites
    has_many :favoritings, through: :favorites, source: :comment
    
    
    def favorite(comment)
        self.favorites.find_or_create_by(comment_id: comment.id)
    end
    
    def unfavorite(comment)
        favorite = self.favorites.find_by(comment_id: comment.id)
        favorite.destroy if favorite
    end    
        
    def favoriting?(comment)
        self.favoritings.include?(comment)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
         redirect_to login_url 
    end
  end      
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @subject = Subject.find(params[:subject_id])
    @comment = @subject.comments.new(comment_params)
    if logged_in?
      @comment.user_id = current_user.id
    else
      @comment.user_id = 1
    end  
    if @comment.save
      flash[:success] = 'コメントを投稿しました。'
      redirect_to @subject
    else
      redirect_to @subject
    end  
  end

  def edit
    @comment = current_user.comments.find_by(id:params[:id])
    @subject = @comment.subject
  end

  def update
    @subject = Subject.find(params[:subject_id])
    @comment = current_user.comments.find_by(id:params[:id])
    if @comment.update(comment_params)
      flash[:success] = "コメントは正常に更新されました。"
      redirect_to @subject
    else
      flash.now[:danger] = "コメントは更新されませんでした。"
      render :@subject
    end  
  end

  def destroy
    @comment = Comment.find(params[:id])
    @subject = @comment.subject 
    Comment.find_by(id: params[:id],subject_id: params[:subject_id]).destroy
    flash[:success] = "コメントは正常に削除されました。"
    redirect_to @subject
  end


  private
  
  
  def comment_params
    params.require(:comment).permit(:message)
  end
  
end  

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  
  def create
    comment = Comment.find(params[:comment_id])
    current_user.favorite(comment)
    flash[:success] = "この投稿をお気に入りにしました。"
    redirect_to root_path
  end

  def destroy
    comment = Comment.find(params[:comment_id])
    current_user.unfavorite(comment)
    flash[:success] = "この投稿をお気に入りから削除しました。"
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
     email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to login_url
  end
  
   private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  before_action :require_user_logged_in, only: [:new, :create, :edit, :update]
  
  def show
    @subject = Subject.find(params[:id])
    @comments = @subject.comments
    if logged_in?
      @comment = current_user.comments.new
    else
      user = User.find(1)
      @comment = user.comments.new
    end
  end

  def new
    @subject = Subject.new
    @comment = Comment.new
  end

  def create
    @subject = current_user.subjects.build(subject_params)
    if @subject.save
      flash[:success] = '掲題を投稿しました。'
      redirect_to root_url
    else
      @subjects = Subject.order(id: :desc).page(params[:page])
      flash.now[:danger] = '掲題の投稿に失敗しました。'
      render new_subject_path
    end  
  end

  def edit
     @subject = current_user.subjects.find(params[:id])
  end
  
  def update
    @subject = current_user.subjects.find_by(id:params[:id])
    if @subject.update(subject_params)
      flash[:success] = "掲題は正常に更新されました。"
      redirect_to @subject
    else
      flash.now[:danger] = "掲題は更新されませんでした。"
      render :edit
    end  
  end
  
  private
  
  def subject_params
    params.require(:subject).permit(:content)
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @subjects = Subject.order(id: :desc).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.order(id: :asc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.favoritings.page(params[:page])
  end  
  
  def my_comments
    @user = User.find(params[:id])
    @my_comments = @user.comments.page(params[:page])
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/comments/_comments.html.erb
<ul class="list-unstyled">
  <% comments.each do |comment| %>
    <li class="media mb-3">
      <div class="media-body">
        <div>
          <%= link_to comment.message, subject_path(comment.subject) %>
        </div>
          <div class='btn-toolbar'>
            <div class="btn-group">
              <% if current_user == comment.user %>
                <%= link_to "Delete", subject_comment_path(comment.subject , comment) , method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
              <% end %>
              <%= render 'favorites/favorite_button', comment: comment  %>
            </div>
          </div>  
      </div>
    </li>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="text-center">
  <h1>コメントを編集する</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with model:[@subject, @comment], local: true do |f| %>
        <%= render 'layouts/error_messages' , model: f.object %>
      
      <div class="form-group">
        <%= f.label :message, 'コメント' %>
        <%= f.text_field :message, class: 'form-control' %>
      </div>
      
      <%= f.submit '投稿する', class: 'btn btn-primary btn-block' %>
      <%= link_to 'このメッセージを削除する', subject_comment_path(@subject , @comment), method: :delete, data: { confirm: '本当に削除してもよろしいですか?' }, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/favorites/_favorite_button.html.erb
<% if current_user.favoriting?(comment) %>
    <%= form_with(model: current_user.favorites.find_by(comment_id: comment.id), local: true, method: :delete) do |f| %>
         <%= hidden_field_tag :comment_id, comment.id %>
         <%= f.submit 'いいねから取り消す', class: 'btn btn-secondary btn-sm' %>
    <% end %>
<% else %>
    <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
        <%= hidden_field_tag :comment_id, comment.id %>
        <%= f.submit 'いいね', class: 'btn btn-primary btn-sm' %>
    <% end %>
<% end %>   

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>    

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">DisucussionBoard</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'ユーザ一覧', users_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '掲題を立てる', new_subject_url, class: 'nav-link' %></li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
                <li class="dropdown-divider"></li>
                <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
        <li class="nav-item"><%= link_to 'signup' , signup_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DiscussionBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class='container'>
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/subjects/_subjects.html.erb
<ul class="list-unstyled">
  <% subjects.each do |subject| %>
    <li class="media mb-3">
      <div class="media-body">
        <div>
          <%= link_to subject.content , subject_path(subject) %>
        </div>
          <div class='btn-toolbar'>
            <div class="btn-group">
              <% if current_user == subject.user %>
                <%= link_to "編集する", new_subject_path, class: 'btn btn-secondary btn-sm' %>
              <% end %>
            </div>
          </div>  
      </div>
    </li>
  <% end %>
</ul>

app/views/subjects/edit.html.erb
<div class="text-center">
  <h1>掲題を編集する</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @subject, local: true) do |f| %>
        <%= render 'layouts/error_messages' , model: f.object %>
      
      <div class="form-group">
        <%= f.label :content, '掲題' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      
      <%= f.submit '投稿する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="text-center">
  <h1>掲題を立てる</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @subject, local: true) do |f| %>
        <%= render 'layouts/error_messages' , model: f.object %>
      
      <div class="form-group">
        <%= f.label :content, '掲題' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      
      <%= f.submit '投稿する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/subjects/show.html.erb
<div class="row">
  <div class="col-sm-7 offset-sm-5">
    <h1><%= @subject.content %></h1>
    <% if current_user == @subject.user%>
        <div class="offset-sm-6">
          <%= link_to 'この掲題を編集する', edit_subject_path(@subject), class: 'btn btn-light' %>
        </div>
    <% end %>      
  </div>
</div>  
  <h3><%= 'コメント一覧' %></h3>
<div class="row">
  <div class="offset-sm-1 col-sm-11">
    <table class="table">
      <% @comments.each do |comment| %>
        <li class="media">
          <div class="media-body">
            <div>
              <%= comment.message %>
            </div>
            <div class='btn-toolbar'>
              <div class="btn-group">
                <% if current_user == comment.user %>
                 <%= link_to 'コメントを編集する' ,edit_subject_comment_path(@subject,comment), class: 'btn btn-light' %> 
                <% end %>
                <% if logged_in? %>
                  <%= render 'favorites/favorite_button', comment: comment  %>
                <% end %>
              </div>
            </div>  
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>  

<div class="row">
  <div class="col-sm-5 offset-sm-7">
    <%= form_with model:[@subject, @comment], local: true do |f| %>
        <%= render 'layouts/error_messages' , model: f.object %>
        
        <div class="form-group">
          <%= f.label :message, 'コメント' %>
          <%= f.text_field :message, class: 'form-control' %>
        </div>
        <%= f.submit 'コメントを投稿する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/toppages/index.html.erb
<div class="center jumbotron">
    <div class="text-center">
        <h1>DisucussionBoard</h1>
    </dib>
</div>        
<% if @subjects.any? %>
    <table class="table table-striped">
        <thead>
          <tr>
            <th class="text-center">id</th>
            <th class="text-left">タイトル</th>
          </tr>
        </thead>
        <tbody>
          <% @subjects.each do |subject| %>
             <tr>
                <td class="text-center"><%= link_to subject.id, subject %></td>
                <td class="text-left"><%= link_to subject.content, subject %></td>
             </tr>
          <% end %>    
        </tbody>
    </table>
    <div>
        <%= paginate @subjects %>  
    </div>
<% end %>

app/views/users/index.html.erb
<ul class="list-unstyled">
  <h2><%= 'ユーザ一覧' %></h2>
  <% @users.each do |user| %>
    <li class="media">
      <div class="media-body">
        <div>
          <h5><p><%= link_to user.id , user_path(user) %> : <%= link_to user.name, user_path(user) %>さん</p></h5>
        </div>
      </div>
    </li>
  <% end %>
</ul>
<%= paginate @users %>

app/views/users/likes.html.erb
<div class="row">
    <aside class="col-sm-4">
        <%= @user.name %> さんの詳細
    </aside>
    <div class="col-sm-8">
        <ul class="nav nav-tabs nav-justified mb-3">
            <li class="nav-item"><a href="<%= my_comments_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(my_comments_user_path(@user)) %>">コメント一覧  <span class="badge badge-secondary"></span></a></li>
            <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">いいね一覧  <span class="badge badge-secondary"></span></a></li>
            <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">立てた掲題一覧  <span class="badge badge-secondary"></span></a></li>
        </ul>
        <%= render 'comments/comments', comments: @likes %>
    </div>
</div>    

app/views/users/my_comments.html.erb
<div class="row">
    <aside class="col-sm-4">
        <h2><%= @user.name %> さんの詳細</h2>
    </aside>
    <div class="col-sm-8">
        <ul class="nav nav-tabs nav-justified mb-3">
            <li class="nav-item"><a href="<%= my_comments_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(my_comments_user_path(@user)) %>">コメント一覧  <span class="badge badge-secondary"></span></a></li>
            <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">いいね一覧  <span class="badge badge-secondary"></span></a></li>
            <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">立てた掲題一覧  <span class="badge badge-secondary"></span></a></li>
        </ul>
        <%= render 'comments/comments', comments: @my_comments %>
    </div>
</div>    

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages' , model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <aside class="col-sm-4">
        <%= @user.name %> さんの詳細
    </aside>
    <div class="col-sm-8">
        <ul class="nav nav-tabs nav-justified mb-3">
            <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">立てた掲題一覧  <span class="badge badge-secondary"></span></a></li>
            <li class="nav-item"><a href="<%= my_comments_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(my_comments_user_path(@user)) %>">コメント一覧  <span class="badge badge-secondary"></span></a></li>
            <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">いいね一覧  <span class="badge badge-secondary"></span></a></li>
        </ul>
        <%= render 'subjects/subjects', subjects: @user.subjects %>
    </div>
</div>    